# Generated by Django 5.0.6 on 2024-08-07 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('ID_domicilio', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=100)),
                ('numero_exterior', models.CharField(max_length=10)),
                ('colonia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('cp', models.CharField(max_length=10)),
                ('ciudad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('ID_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('universidad', models.CharField(max_length=100)),
                ('carrera', models.CharField(max_length=100)),
                ('rol', models.IntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('INE', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('CURP', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('COMPROBANTE_DOMICILIO', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('ACTA_NACIMIENTO', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('CONSTANCIA_DERECHOS', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('ID_domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='residentes.domicilio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('ID_contacto', models.AutoField(primary_key=True, serialize=False)),
                ('contacto', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('ID_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
