# Generated by Django 5.0.7 on 2024-08-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0002_alter_usuario_id_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.IntegerField(default=1),
        ),
    ]
