# Generated by Django 5.0.7 on 2024-08-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0003_alter_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.FileField(upload_to='')),
            ],
        ),
    ]
