# Generated by Django 5.0.7 on 2024-08-15 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0004_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='url',
        ),
        migrations.AddField(
            model_name='documento',
            name='archivo',
            field=models.FileField(default='documentos/default.txt', upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='nombre',
            field=models.CharField(max_length=255),
        ),
    ]
