# Generated by Django 5.0.7 on 2025-06-27 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residentes', '0006_alter_documento_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sensor_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
